### ISSUE TITLE
webauthinfra_ipa_1 exited with code 15

### ISSUE THREAD

**Issue by selukov** [adelton/webauthinfra#10]
I'm trying to start docker but getting an error
root@example:~/work/webauthinfra# docker-compose up
Starting webauthinfra_ipa_1 ... done
Attaching to webauthinfra_ipa_1
ipa_1  | Configuring ipa ...
ipa_1  | Container invoked without fully-qualified hostname
ipa_1  |    and without specifying hostname to use.
ipa_1  | Consider using -h FQDN option to docker run.
webauthinfra_ipa_1 exited with code 15

Please help me

**Comment by adelton** [comment]
What version of docker-compose and docker do you use, and on what OS?

**Comment by selukov** [comment]
I tried on Centos 7.7 (1908) and Ubuntu 16.04
Ubuntu 16.04 has 
```
$► docker -v
Docker version 19.03.8, build afacb8b7f0
$► docker-compose -v
docker-compose version 1.22.0, build f46880fe
```
Centos 7.7 has
```
[root@osboxes webauthinfra]# docker -v
Docker version 19.03.8, build afacb8b
[root@osboxes webauthinfra]# docker-compose -v
docker-compose version 1.25.4, build 8d51620a
```

**Comment by adelton** [comment]
If you change to some new directory, create file `docker-compose.yml` with content
```
version: '2.1'
services:
    test:
        image: registry.fedoraproject.org/fedora:31
        hostname: ipa
        domainname: example.test
        entrypoint: uname -n
```
and run
`docker-compose up` -- what does it print out?
